steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/twenty:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/twenty:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/twenty:proxy-auth'
      - '-f'
      - 'packages/twenty-docker/twenty/Dockerfile'
      - '--build-arg'
      - 'REACT_APP_SERVER_BASE_URL=https://crm.mereka.io'
      - '.'
    timeout: '3600s'

images:
  - 'gcr.io/$PROJECT_ID/twenty:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/twenty:latest'
  - 'gcr.io/$PROJECT_ID/twenty:proxy-auth'

timeout: '7200s'
options:
  machineType: 'E2_HIGHCPU_8'
